In [2]:
import pandas as pd
import numpy as np
dataset=pd.read_csv("User_Data.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset['Gender']=dataset["Gender"].map({"Male":0,"Female":1}).astype(int)
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       0   19            19000          0
1    15810944       0   35            20000          0
2    15668575       1   26            43000          0
3    15603246       1   27            57000          0
4    15804002       0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       1   46            41000          1
396  15706071       0   51            23000          1
397  15654296       1   50            20000          1
398  15755018       0   36            33000          0
399  15594041       1   49            36000          1

[400 rows x 5 columns]

In [5]:
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values
print(x,y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [5]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25)

In [6]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
xtrain=sc_x.fit_transform(xtrain)
xtest=sc_x.transform(xtest)
print(xtrain[0:10, :])
print(xtest[0:10, :])

[[ 0.17234521  1.88218779]
 [-0.96608186  0.54296678]
 [ 0.17234521  0.04803728]
 [-0.96608186  0.60119378]
 [ 1.02616551  1.79484729]
 [-1.25068863 -1.23295674]
 [-1.06095079 -1.00004874]
 [-0.20713048 -1.43675124]
 [ 1.02616551  1.9986418 ]
 [-0.11226156  0.16449128]]
[[-1.25068863 -1.34941074]
 [-0.87121294 -1.08738924]
 [-0.77634402  0.31005878]
 [ 0.93129659  1.27080429]
 [ 1.12103444 -0.97093524]
 [ 0.17234521 -0.79625423]
 [-0.20713048 -0.33043823]
 [ 0.36208306 -0.50511923]
 [-1.72503325 -1.40763774]
 [-0.49173725  1.38725829]]


In [7]:
from sklearn.linear_model import LogisticRegression
Classifier=LogisticRegression(random_state=0)
Classifier.fit(xtrain,ytrain)

LogisticRegression(random_state=0)

In [8]:
import pickle
with open ("Logistic_model.pkl","wb") as files:
    pickle.dump(Classifier, files)
with open("Logistic_model.pkl","rb") as f:
    Classifier=pickle.load(f)
y_pred=Classifier.predict(xtest)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [9]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,y_pred)
print("confusion matrix:\n" , cm)

confusion matrix:
 [[49  8]
 [14 29]]


In [10]:
from sklearn.metrics import accuracy_score
print("accuracy:", accuracy_score(ytest,y_pred))

accuracy: 0.78


In [11]:
from sklearn.metrics import precision_score
print("precision:", precision_score(ytest,y_pred))

precision: 0.7837837837837838


In [12]:
from sklearn.metrics import recall_score
print("recall score:", recall_score(ytest,y_pred))

recall score: 0.6744186046511628
